spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/ticket?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true
        hbm2ddl.auto: validate

#logging:
#  level:
#    org.hibernate.SQL: DEBUG      # SQL 쿼리 출력
#    org.hibernate.orm.jdbc.bind: TRACE  # 바인딩된 실제 값 출력
