version: "3.9"
services:
  db:
    image: mysql:8.0.28
    container_name: ticket-mysql
    platform: linux/x86_64
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init/schema.sql:/docker-entrypoint-initdb.d/schema.sql
